[package]
name = "fable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is_executable = "1.0.1"
walkdir = "2.3.2"

[features]
